name: VeryStaff
version: '${project.version}'
main: fr.verymc.Main
authors: [ Farmeurimmo, seyfle ]
softdepend: [ IridiumSkyblock, Citizens ]
commands:
  mod:
    permission: mod.use
  cps:
    permission: cps.use
  s:
    permission: s.base
  freeze:
    permission: freeze.use
  vanish:
    permission: vanish.use
